# Generated by Django 4.0.2 on 2022-04-09 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCountry',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
        ),
    ]
