# Generated by Django 4.0.2 on 2022-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dataset_languagesample_synthesizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagecountry',
            name='country',
        ),
        migrations.AddField(
            model_name='languagecountry',
            name='country',
            field=models.ManyToManyField(to='app.Country'),
        ),
        migrations.RemoveField(
            model_name='languagecountry',
            name='language',
        ),
        migrations.AddField(
            model_name='languagecountry',
            name='language',
            field=models.ManyToManyField(to='app.Language'),
        ),
    ]
