# Generated by Django 4.0.2 on 2022-04-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_lang_id_dataset_lang_remove_language_lang_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='countries',
            field=models.ManyToManyField(to='app.Country'),
        ),
        migrations.DeleteModel(
            name='LanguageCountry',
        ),
    ]
