# Generated by Django 4.0.2 on 2022-04-14 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_languagesample_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesizeRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=3000)),
                ('audio_format', models.CharField(choices=[('mp3', 'mp3'), ('wav', 'wav')], max_length=3)),
                ('synth_id', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
