# Generated by Django 4.0.2 on 2022-04-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_synthesizerequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SynthesizeRequest',
            new_name='SynthesizeRequestModel',
        ),
    ]
