# Generated by Django 4.0.2 on 2022-04-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_synthesizerequest_synthesizerequestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthesizerequestmodel',
            name='audio_format',
            field=models.CharField(choices=[('mp3', 'mp3'), ('wav', 'wav')], default='mp3', max_length=3),
        ),
        migrations.AlterField(
            model_name='synthesizerequestmodel',
            name='synth_id',
            field=models.CharField(choices=[], default='', max_length=100),
        ),
    ]
