# Generated by Django 4.0.2 on 2022-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_synthesizerequestmodel_synth_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lang_wikipedia_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
