# Generated by Django 4.0.2 on 2022-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_language_lang_wikipedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesizer',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
