# Generated by Django 4.0.2 on 2022-04-24 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_dataset_data_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('licence', models.CharField(blank=True, max_length=100)),
                ('num_languages', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
