# Generated by Django 4.0.2 on 2022-04-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_sources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sources',
            new_name='DataSource',
        ),
    ]
